### ISSUE TITLE
How to scroll ion-grid using specific grid to scroll that specific grid in ionic 3? 

### ISSUE THREAD

**Issue by binita12345** [KillerCodeMonkey/ionicScroller#3]

**Comment by binita12345** [comment]
I want to scroll bottom grids on click of first grid images, I have 4 images in first grid and another 4 grid for description of particular images. I want to scroll specific grid o click of specific image, respectively.
so How can i scroll grid using click event in ionic3?

**Comment by KillerCodeMonkey** [comment]
Check the Documentation of Ion content and scroll. They have scrollTo
functions. So Get the Position of the Element and Call IT. But That is more
a question for the ionic Forum. Because this little helper is for ionic 1

binita12345 <notifications@github.com> schrieb am Sa., 14. Apr. 2018, 11:13:
